language: node_js
node_js:
- '0.10'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update -qq
before_script:
- npm install -g karma karma-cli
deploy:
  provider: appfog
  email: gvg.fede@gmail.com
  password:
    secure: lWTbCUB+JAZ7KG2m+KsJsQhF0H99I68kw7s75epaFucjGZuyPUNrcPmLcqkEefHXTSL8kMRRKXBxQmiW3rmBDvQiPCP02alDMW/YYRaEo6HI2C33/L/g59/OafoTefd33OYiwOqtWvvhhr63x9QwqlVO60OgCSBw62hoeCDGJNY=
  app: planets-demo
  on:
    repo: Meesayen/planets-demo
